/*
 * module_address.h
 *
 *  Created on: Jun 22, 2024
 *      Author: jules
 */

#ifndef INC_MODULE_ADDRESS_H_
#define INC_MODULE_ADDRESS_H_

#include <stdio.h>

#include "stm32c0xx_hal.h"

/*

[4096 -- 3840][3839 -- 3585][ 3854 -- 3585] ...

*/

/*
#define SOCKET_0_ADDRESS (0x01)
#define SOCKET_0_ADDRESS_ADC_MAX (0x1000)
#define SOCKET_0_ADDRESS_ADC_MIN (SOCKET_0_ADDRESS_ADC_MAX - 200)

#define SOCKET_1_ADDRESS (0x02)
#define SOCKET_1_ADDRESS_ADC_MAX (SOCKET_0_ADDRESS_ADC_MIN - 1)
#define SOCKET_1_ADDRESS_ADC_MIN (SOCKET_1_ADDRESS_ADC_MAX - 255)

#define SOCKET_2_ADDRESS (0x03)
#define SOCKET_2_ADDRESS_ADC_MAX (SOCKET_1_ADDRESS_ADC_MIN - 1)
#define SOCKET_2_ADDRESS_ADC_MIN (SOCKET_2_ADDRESS_ADC_MAX - 255)

#define SOCKET_3_ADDRESS (0x04)
#define SOCKET_3_ADDRESS_ADC_MAX (SOCKET_2_ADDRESS_ADC_MIN - 1)
#define SOCKET_3_ADDRESS_ADC_MIN (SOCKET_3_ADDRESS_ADC_MAX - 255)

#define SOCKET_4_ADDRESS (0x05)
#define SOCKET_4_ADDRESS_ADC_MAX (SOCKET_3_ADDRESS_ADC_MIN - 1)
#define SOCKET_4_ADDRESS_ADC_MIN (SOCKET_4_ADDRESS_ADC_MAX - 255)

#define SOCKET_5_ADDRESS (0x06)
#define SOCKET_5_ADDRESS_ADC_MAX (SOCKET_4_ADDRESS_ADC_MIN - 1)
#define SOCKET_5_ADDRESS_ADC_MIN (SOCKET_5_ADDRESS_ADC_MAX - 255)

#define SOCKET_6_ADDRESS (0x07)
#define SOCKET_6_ADDRESS_ADC_MAX (SOCKET_5_ADDRESS_ADC_MIN - 1)
#define SOCKET_6_ADDRESS_ADC_MIN (SOCKET_6_ADDRESS_ADC_MAX - 255)

#define SOCKET_7_ADDRESS (0x08)
#define SOCKET_7_ADDRESS_ADC_MAX (SOCKET_6_ADDRESS_ADC_MIN - 1)
#define SOCKET_7_ADDRESS_ADC_MIN (SOCKET_7_ADDRESS_ADC_MAX - 255)

#define SOCKET_8_ADDRESS (0x09)
#define SOCKET_8_ADDRESS_ADC_MAX (SOCKET_7_ADDRESS_ADC_MIN - 1)
#define SOCKET_8_ADDRESS_ADC_MIN (SOCKET_8_ADDRESS_ADC_MAX - 255)

#define SOCKET_9_ADDRESS (0x0A)
#define SOCKET_9_ADDRESS_ADC_MAX (SOCKET_8_ADDRESS_ADC_MIN - 1)
#define SOCKET_9_ADDRESS_ADC_MIN (SOCKET_9_ADDRESS_ADC_MAX - 255)

#define SOCKET_10_ADDRESS (0x0B)
#define SOCKET_10_ADDRESS_ADC_MAX (SOCKET_9_ADDRESS_ADC_MIN - 1)
#define SOCKET_10_ADDRESS_ADC_MIN (SOCKET_10_ADDRESS_ADC_MAX - 255)

#define SOCKET_11_ADDRESS (0x0C)
#define SOCKET_11_ADDRESS_ADC_MAX (SOCKET_10_ADDRESS_ADC_MIN - 1)
#define SOCKET_11_ADDRESS_ADC_MIN (SOCKET_11_ADDRESS_ADC_MAX - 255)

#define SOCKET_12_ADDRESS (0x0D)
#define SOCKET_12_ADDRESS_ADC_MAX (SOCKET_11_ADDRESS_ADC_MIN - 1)
#define SOCKET_12_ADDRESS_ADC_MIN (SOCKET_12_ADDRESS_ADC_MAX - 255)

#define SOCKET_13_ADDRESS (0x0E)
#define SOCKET_13_ADDRESS_ADC_MAX (SOCKET_12_ADDRESS_ADC_MIN - 1)
#define SOCKET_13_ADDRESS_ADC_MIN (SOCKET_13_ADDRESS_ADC_MAX - 255)

#define SOCKET_14_ADDRESS (0x0F)
#define SOCKET_14_ADDRESS_ADC_MAX (SOCKET_13_ADDRESS_ADC_MIN - 1)
#define SOCKET_14_ADDRESS_ADC_MIN (SOCKET_14_ADDRESS_ADC_MAX - 255)

#define SOCKET_15_ADDRESS (0x10)
#define SOCKET_15_ADDRESS_ADC_MAX (SOCKET_14_ADDRESS_ADC_MIN - 1)
#define SOCKET_15_ADDRESS_ADC_MIN (SOCKET_15_ADDRESS_ADC_MAX - 255)
*/


#define SOCKET_0_ADDRESS (0x01)
#define SOCKET_0_ADDRESS_ADC_MAX (0x1000)
#define SOCKET_0_ADDRESS_ADC_MIN (3886)

#define SOCKET_1_ADDRESS (0x02)
#define SOCKET_1_ADDRESS_ADC_MAX (SOCKET_0_ADDRESS_ADC_MIN)
#define SOCKET_1_ADDRESS_ADC_MIN (3436)

#define SOCKET_2_ADDRESS (0x03)
#define SOCKET_2_ADDRESS_ADC_MAX (SOCKET_1_ADDRESS_ADC_MIN)
#define SOCKET_2_ADDRESS_ADC_MIN (3037)

#define SOCKET_3_ADDRESS (0x04)
#define SOCKET_3_ADDRESS_ADC_MAX (SOCKET_2_ADDRESS_ADC_MIN)
#define SOCKET_3_ADDRESS_ADC_MIN (2756)

#define SOCKET_4_ADDRESS (0x05)
#define SOCKET_4_ADDRESS_ADC_MAX (SOCKET_3_ADDRESS_ADC_MIN)
#define SOCKET_4_ADDRESS_ADC_MIN (2520)

#define SOCKET_5_ADDRESS (0x06)
#define SOCKET_5_ADDRESS_ADC_MAX (SOCKET_4_ADDRESS_ADC_MIN)
#define SOCKET_5_ADDRESS_ADC_MIN (2291)

#define SOCKET_6_ADDRESS (0x07)
#define SOCKET_6_ADDRESS_ADC_MAX (SOCKET_5_ADDRESS_ADC_MIN)
#define SOCKET_6_ADDRESS_ADC_MIN (2070)

#define SOCKET_7_ADDRESS (0x08)
#define SOCKET_7_ADDRESS_ADC_MAX (SOCKET_6_ADDRESS_ADC_MIN)
#define SOCKET_7_ADDRESS_ADC_MIN (1857)

#define SOCKET_8_ADDRESS (0x09)
#define SOCKET_8_ADDRESS_ADC_MAX (SOCKET_7_ADDRESS_ADC_MIN)
#define SOCKET_8_ADDRESS_ADC_MIN (1643)

#define SOCKET_9_ADDRESS (0x0A)
#define SOCKET_9_ADDRESS_ADC_MAX (SOCKET_8_ADDRESS_ADC_MIN)
#define SOCKET_9_ADDRESS_ADC_MIN (1434)

#define SOCKET_10_ADDRESS (0x0B)
#define SOCKET_10_ADDRESS_ADC_MAX (SOCKET_9_ADDRESS_ADC_MIN)
#define SOCKET_10_ADDRESS_ADC_MIN (1231)

#define SOCKET_11_ADDRESS (0x0C)
#define SOCKET_11_ADDRESS_ADC_MAX (SOCKET_10_ADDRESS_ADC_MIN)
#define SOCKET_11_ADDRESS_ADC_MIN (1040)

#define SOCKET_12_ADDRESS (0x0D)
#define SOCKET_12_ADDRESS_ADC_MAX (SOCKET_11_ADDRESS_ADC_MIN)
#define SOCKET_12_ADDRESS_ADC_MIN (857)

#define SOCKET_13_ADDRESS (0x0E)
#define SOCKET_13_ADDRESS_ADC_MAX (SOCKET_12_ADDRESS_ADC_MIN)
#define SOCKET_13_ADDRESS_ADC_MIN (670)

#define SOCKET_14_ADDRESS (0x0F)
#define SOCKET_14_ADDRESS_ADC_MAX (SOCKET_13_ADDRESS_ADC_MIN)
#define SOCKET_14_ADDRESS_ADC_MIN (475)

#define SOCKET_15_ADDRESS (0x10)
#define SOCKET_15_ADDRESS_ADC_MAX (SOCKET_14_ADDRESS_ADC_MIN)
#define SOCKET_15_ADDRESS_ADC_MIN (0)

#define DEVICE_ADDRESS_MEASURE_COUNT 16

uint8_t get_device_address_stable(ADC_HandleTypeDef *adc_handle);
uint32_t get_socket_adc_value(ADC_HandleTypeDef *adc_handle);
uint8_t get_device_address(ADC_HandleTypeDef *adc_handle);
uint8_t adc_value_to_address(uint32_t adc_value);

#endif /* INC_MODULE_ADDRESS_H_ */
